# Generated by Django 4.1.7 on 2023-11-15 02:38

from django.db import migrations, models
import django_nh3.models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Nh3Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_nh3.models.Nh3Field()),
                ("blank_field", django_nh3.models.Nh3Field(blank=True)),
                (
                    "null_field",
                    django_nh3.models.Nh3Field(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nh3NullableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    django_nh3.models.Nh3Field(
                        choices=[("f", "first choice"), ("s", "second choice")]
                    ),
                ),
                ("content", django_nh3.models.Nh3Field(blank=True, null=True)),
            ],
        ),
    ]
