# Generated by Django 4.1.7 on 2023-11-15 02:38

from django.db import migrations, models
import django_nh3.models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="Nh3CharFieldContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_nh3.models.Nh3CharField(max_length=1000)),
                (
                    "blank_field",
                    django_nh3.models.Nh3CharField(blank=True, max_length=1000),
                ),
                (
                    "null_field",
                    django_nh3.models.Nh3CharField(
                        blank=True, null=True, max_length=1000
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nh3TextFieldContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", django_nh3.models.Nh3TextField(max_length=1000)),
                (
                    "blank_field",
                    django_nh3.models.Nh3TextField(blank=True, max_length=1000),
                ),
                (
                    "null_field",
                    django_nh3.models.Nh3TextField(
                        blank=True, null=True, max_length=1000
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nh3CharFieldNullableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    django_nh3.models.Nh3CharField(
                        blank=True,
                        choices=[("f", "first choice"), ("s", "second choice")],
                        max_length=1000,
                    ),
                ),
                (
                    "content",
                    django_nh3.models.Nh3CharField(
                        blank=True, null=True, max_length=1000
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nh3TextFieldNullableContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    django_nh3.models.Nh3TextField(
                        blank=True,
                        choices=[("f", "first choice"), ("s", "second choice")],
                        max_length=1000,
                    ),
                ),
                (
                    "content",
                    django_nh3.models.Nh3TextField(
                        blank=True, null=True, max_length=1000
                    ),
                ),
            ],
        ),
    ]
