name: Ruff

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: python -Im pip install --user ruff

    - name: Run ruff
      working-directory: ./src
      run: ruff check --output-format=github django_nh3
